# Generated by Django 5.2.8 on 2025-12-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_noticia_link_alter_noticia_sumario'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='automatizada',
            field=models.BooleanField(default=False),
        ),
    ]
