# Generated by Django 5.2.8 on 2025-12-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_noticia_automatizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='link',
            field=models.URLField(max_length=256, null=True),
        ),
    ]
