# Generated by Django 5.2.8 on 2025-12-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_automatizada_noticia_automatizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='link',
            field=models.URLField(max_length=256, null=True),
        ),
    ]
