# Generated by Django 5.2.8 on 2025-12-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='link',
            field=models.URLField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='sumario',
            field=models.TextField(max_length=500),
        ),
    ]
