# Generated by Django 5.2.8 on 2025-12-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_noticia_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='automatizada',
            new_name='automatizado',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='link',
            field=models.URLField(max_length=512, null=True),
        ),
    ]
